spring.application.name=moviebooking

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.app.jwtSecret=mySecretKey123912738vhgvggyg87huhbg8ig8f76f7tf76y
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=springBootMovieBookingSystem

project.image=images/

logging.level.org.springframework.security=DEBUG